### ISSUE TITLE
Fabric forcing password when not required

### ISSUE THREAD

**Issue by chrisspen** [ploxiln/fab-classic#81]
I recently upgraded Ubuntu and fab-classic versions, and now old code that used to work is failing because Fabric is now demanding a password when none is required.

    chris@localhost:~$ ssh chris@localhost
    Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
    chris@localhost:~$ exit
    Connection to localhost closed.
    chris@localhost:~$ . .env/bin/activate
    (.env) chris@localhost:~$ pip freeze | grep fab-classic
    fab-classic==1.19.2
    (.env) chris@localhost:~$ python
    (.env) chris@localhost:~$ python
    Python 3.12.1 (main, Dec 10 2023, 15:07:36) [GCC 11.4.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from fabric.api import run, env
    /home/chris/git/burlap/.env/lib/python3.12/site-packages/paramiko/transport.py:178: CryptographyDeprecationWarning: Blowfish has been deprecated
      'class': algorithms.Blowfish,
    >>> env.host_string = 'localhost'; result = run('uname -s')
    [localhost] run: uname -s
    Connect error: Authentication failed.
    [localhost] Login password for 'chris': 

Why is Fabric asking for a password when my localhost doesn't require one for that user?

**Comment by ploxiln** [comment]
This is probably related to _paramiko_ (for fab-classic that would be https://github.com/ploxiln/paramiko-ng by default).

Did it use ssh key (or agent with key) for auth before? If it was an rsa key, it's possible that updated ubuntu's openssh server requires rsa-sha-256 (protocol change for rsa keys) instead of classic rsa protocol which used sha1. Or maybe updated ubuntu's openssh server config has some other newer security measure like "disable with empty password" (though that was default for a long time, maybe you customized it and it was reverted ...)

Anyway, this is between paramiko and the ssh server, you could try older versions of paramiko-ng (or fab-classic if you want), and check your ssh-server config.
